apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-secrets
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.env.dbPassword | quote }}
  RABBITMQ_PASSWORD: {{ .Values.env.rabbitmqPassword | quote }}
