version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=sa
      - RABBITMQ_DEFAULT_PASS=sa
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - 5672:5672
      - 15672:15672
