management:
  server:
    port: 9081
  user:
    name: admin
    password: 'admin'
  trace:
    http:
      enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        enabled: false
      prometheus:
        enabled: true
