management:
  server:
    port: 9081
  user:
    name: admin
    password: 'admin'
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  influx:
    metrics:
      export:
        enabled: false
  prometheus:
    metrics:
      export:
        enabled: true
  httpexchanges:
    recording:
      enabled: false
