spring:
  mail:
    host: localhost
    port: 25
    username: test@test.com
    password: password
    template:
      order-confirmation: order-confirmation-attachment.fo.ftl
      order-customer: order-confirmation.ftl.txt
      pdf-path: pdf
      email-path: email
    transport:
      protocol: smtp
    default-encoding: UTF-8
    debug: false
    from: Test <test@test.com>
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000
          starttls:
            enable: true
