spring:
    config:
        import:
            classpath:application-persistence.yml
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: true
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        username: sa
        password:
        driverClassName: org.h2.Driver
        pool:
            tomcat:
                min-idle: 1
                max-idle: 10
                test-on-borrow: false
                test-on-return: false
                validation-query: SELECT 1
    jpa:
        database: H2
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate.default_schema: test_db
