version: "3.9"
services:
  postgres:
    image: centos/postgresql-96-centos7
    restart: always
    environment:
      - POSTGRESQL_USER=sa
      - POSTGRESQL_PASSWORD=sa
      - POSTGRESQL_DATABASE=test_db
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - 5432:5432
